name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      # Setup pnpm and Node.js, caching pnpm store
      - name: 🅿️ Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: 🟢 Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22 # Or your preferred Node.js version
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      # Cache Biome for faster formatting
      - name: ⚡ Cache Biome
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cache/biome
          key: ${{ runner.os }}-biome-${{ hashFiles('**/biome.json') }}
          restore-keys: |
            ${{ runner.os }}-biome-

      - name: ✨ Format code
        run: pnpm fmt

      - name: 📦 Format package.json
        run: npx --yes sort-package-json "package.json" "packages/*/package.json"

      - name: 📚 Format Docs 
        run: pnpm fmt:docs

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c